site_name: 'bool wiki'
site_description: 'BoolBang Wiki'

# repo_url: https://github.com/noraj/mkdocs-windmill-dark

theme:
    name: windmill-dark
    static_templates:
        - 404.html
    include_search_page: true
    search_index_only: true
    history_buttons: true
    article_nav_top: true
    article_nav_bottom: true

docs_dir: docs



nav:
    - Index: index.md
    - Fine Art: 
        - CV: customization.md
        - 비평글:
            - 2016: critic2016.md
            - 2017(1): critic1.md
            - 2017(2): critic2.md
            - 2017(3): critic3.md
            - 2017(전시서문): hamtext.md
            
    - Web:
        - S.U.P Gang-Jin: sample-a.md
        - Horse Citizen:
            - Sample Subpage A1: sample-a1.md
            - Sample Subpage A2: sample-a2.md
        - BoolBang: sample-b.md

markdown_extensions:
    - toc:
        permalink: '#'
    - nl2br 

extra:
    version: 0.1.4
